development:
  adapter: postgresql
  database: snipit_development
  pool: 5
  timeout: 5000

test:
  adapter: postgresql
  database: snipit_test
  pool: 5
  timeout: 5000

production:
  adapter: postgresql
  database: snipit_production
  pool: 5
  timeout: 5000
